[phases.setup]
nixPkgs = ['nodejs_20', 'openssl']
nixpkgsArchive = 'a343533bccc62400e8a9560423486a3b6c11a23b'

[phases.install]
cmds = ['cd backend && npm install']

[phases.build]
cmds = ['cd backend && npx prisma generate && npm run build']

[start]
cmd = 'cd backend && npm run start:prod'

[variables]
NODE_ENV = 'production'
DATABASE_URL = 'postgresql://placeholder:placeholder@placeholder:5432/placeholder?schema=public'
