[phases.setup]
nixPkgs = ['nodejs-20_x', 'openssl']

[nixpacks.node]
version = '20.11.1'

[phases.install]
cmds = ['cd backend && npm install']

[phases.build]
cmds = ['cd backend && npx prisma generate && npm run build']

[start]
cmd = 'cd backend && npm run start:prod'

[variables]
NODE_ENV = 'production'
DATABASE_URL = 'postgresql://placeholder:placeholder@placeholder:5432/placeholder?schema=public'
